#-------------------------------
# General Site Settings
title: Lucas Gatsas
logo: '/images/logo.png'
description: My Name is Lucas Gatsas, I’m a Astro + Solar Photographer based in Switzerland. I like being at the center of TSE events.
baseurl: "https://lucasgatsas.com" 
url: "https://lucasgatsas.com" 

# The subpath of your site, e.g. /blog
# The base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# Author Settings
author:
  avatar: '/images/01.jpg'
  name: Lucas Gatsas
  givenName: Lucas 
  familyName: Gatsas
  job: Astro + Solar Photographer
  socialName: lucasgatsas

social:
- {icon: "ion-logo-twitter", link: "https://twitter.com/lucasgatsas"}
- {icon: "ion-logo-facebook", link: "https://facebook.com"}
- {icon: "ion-logo-youtube", link: "https://youtube.com/@lucasgatsasastro"}
- {icon: "ion-logo-instagram", link: "https://instagram.com/lucasgatsas"}
- {icon: "ion ion-logo-github", link: "https://github.com/spaceg"}

# Example of adding a new link to the author section and footer - {icon: "ion-logo-pinterest", link: "https://pinterest.com"}
# Other icons can be found at https://ionicons.com/v4/



#-------------------------------
# Featured Slider
slider: true # NOTE - By default, the slider is set to display featured posts. To add featured post to the slider, add the field, featured: true in the YAML front matter block. If you do not want to use the slider, leave the slider field empty.


#-------------------------------
# Contact Settings
contact:
  email: lucasgatsas@protonmail.com # Add your email for contant form
  description:  If you have any Questions, feel free to contact me. Otherwise follow my Social Media. # Add a description of your form

# NOTE
# Bonso comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus-identifier:  # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: true # To enable the mailchimp form, use the value true. To turn off use the value false.
mailchimp-text: Subscribe to our newsletter and we’ll send you the emails of latest posts. # Add your description.
mailchimp-identifier:  tse262728.us22.list-manage.com/subscribe/post?u=45108eb6e38b793af7d3de7a6&amp;id=397785b79c


#-------------------------------
# Build settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 8
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  /:title

sass:
  sass_dir: _sass
  style: compressed